name: smarttest
on:
  push:
permissions:
  attestations: write
  contents: read
  id-token: write
  packages: write
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        id: build-push
        uses: docker/build-push-action@v6
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: "{{defaultContext}}:smarttest"
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/${{ github.actor }}/smarttest:latest
      - name: Attest build provenance
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: "ghcr.io/${{ github.actor }}/smarttest"
          subject-digest: ${{ steps.build-push.outputs.digest }}
          push-to-registry: true
