name: smarttest
on:
  push:
permissions:
  contents: read
  packages: write
  id-token: write
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.6.0
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Get container metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.actor }}/smarttest
      - name: Build and push
        id: build-push
        uses: docker/build-push-action@v6
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: "{{defaultContext}}:smarttest"
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/${{ github.actor }}/smarttest:latest
      - name: Cosign
        id: cosign
        run: |
          cosign sign --yes ghcr.io/${{ github.actor }}/smarttest@${{ steps.build-push.outputs.DIGEST }}
      - name: Attest build provenance
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: "ghcr.io/${{ github.actor }}/smarttest"
          subject-digest: ${{ steps.build-push.outputs.digest }}
          push-to-registry: true
